- name: install icinga2 client packages and dependencies
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - icinga2
    - nagios-plugins-disk
    - nagios-plugins-load
    - nagios-plugins-users
    - nagios-plugins-procs
    - nagios-plugins-swap
    - nagios-plugins-check_iostat
    - bc
    - sysstat

- name: icinga2 client config
  template:
    src: icinga2_client.conf
    dest: /etc/icinga2/client.conf

- name: icinga2 commands
  template:
    src: "{{ item }}.cfg"
    dest: "/etc/icinga2/conf.d/{{ item }}.conf"
  with_items:
    - users
    - disk
    - procs
    - load
    - swap
    - iostat

- name: restart icinga2 daemon
  service:
    name: icinga2
    state: restarted
    enabled: yes
