- name: install icinga2 packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - icinga2-common
    - icinga2-bin
    - icinga2
    - nrpe
    - nagios-plugins
    - nagios-plugins-ping
    - nagios-plugins-nrpe
    - nagios-plugins-disk
    - nagios-plugins-load
    - nagios-plugins-users
    - nagios-plugins-procs
    - nagios-plugins-swap
    - nagios-plugins-ssh
    - nagios-plugins-tcp
    - nagios-plugins-check_rbl
    - nagios-plugins-by_ssh
    - nagios-plugins-dig
    - nagios-plugins-http
    - nagios-plugins-smtp
    - nagios-plugins-dns
    - nagios-plugins-check_cups_queue
    - nagios-plugins-check_sip
    - nagios-plugins-dhcp
    - nagios-plugins-snmp

- name: copy main icinga2 configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/icinga2/{{ item }}"
    owner: icinga
    group: icinga
    mode: 0550
    setype: etc_t
  with_items:
    - icinga2.conf
    - zones.conf
    - constants.conf

- name: copy features configuration files into icinga2 feature activation directory
  template:
    src: "{{ item }}"
    dest: "/etc/icinga2/features-available/{{ item }}"
  with_items:
     - api.conf

- name: activate icinga2 features
  command: "/sbin/icinga2-enable-feature {{ item }}"
  with_items:
     - api

- name: check if a configuration already exists
  stat:
    path: /etc/icinga2/conf.d/templates.conf
  register: defaultconfig

- name: remove default configuration
  file:
    dest: /etc/icinga2/conf.d
    state: absent
  when: defaultconfig.stat.isdir is defined and defaultconfig.stat.isdir == false

- name: create configuration directory
  file:
    dest: /etc/icinga2/conf.d
    owner: icinga
    group: icinga
    mode: 0550
    setype: etc_t
    state: directory

- name: create the conf.d folders
  file:
    dest: "/etc/icinga2/{{ item }}"
    owner: icinga
    group: icinga
    mode: 0550
    setype: etc_t
    state: directory
  with_items:
    - conf.d
    - conf.d/hosts
    - conf.d/templates/
    - conf.d/commands/

- name: copy templated icinga2 config files
  template:
    src: "{{ item.src }}"
    dest: "/etc/icinga2/conf.d/{{ item.dest }}"
    owner: icinga
    group: icinga
    mode: 0550
    setype: etc_t
  with_items:
    - src: users.conf
      dest: users.conf
    - src: timeperiods.conf
      dest: timeperiods.conf
    - src: downtimes.conf
      dest: downtimes.conf
    - src: groups.conf
      dest: groups.conf
    - src: commands_check.conf
      dest: commands/check.conf
    - src: commands_notifications.conf
      dest: commands/notifictions.conf
    - src: templates_users.conf
      dest: templates/users.conf
    - src: templates_services.conf
      dest: templates/services.conf
    - src: templates_hosts.conf
      dest: templates/hosts.conf
    - src: templates_schedules.conf
      dest: templates/schedules.conf
    - src: templates_notifications.conf
      dest: templates/notifications.conf

- name: create the pki folders
  action: file dest=/etc/icinga2/pki owner=icinga group=icinga mode=550 setype=etc_t state=directory

- name: copy certificates, key and ca file in the pki folder
  copy:
    src: "/drives/datadrive/.ansible/icinga2cert/{{ item }}"
    dest: "/etc/icinga2/pki/{{ item }}"
  with_items:
    - ca.crt
    - "{{ inventory_hostname }}.crt"
    - "{{ inventory_hostname }}.key"
