/*
 * --------------------------------------------------
 * VanTosh Icinga2 Templates Contacts File
 * (c) copyleft 2013 VanTosh
 * Author: Toshaan Bharvani <toshaan@vantosh.com>
 * --------------------------------------------------
 * {{ ansible_managed }}
 */


library "db_ido_pgsql"


object IdoPgsqlConnection "ido-pgsql" {
  user = "icinga2"
  password = "2icinga2"
  host = "localhost"
  database = "icinga2db"
}
